driver:
  name: docker
  use_sudo: false
  privileged: true
  ssh_timeout: 5
  ssh_retries: 5
  public_key: .kitchen/id_ed25519.pub
  private_key: .kitchen/id_ed25519
  forward:
    - 80

transport:
  name: docker
  log_level: :debug

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_version: 3005.1
  salt_bootstrap_url: https://bootstrap.saltproject.io
  salt_bootstrap_options: -X -x python3 -p git -p curl -p sudo stable 3005.1
  is_file_root: true
  require_chef: false
  salt_copy_filter:
    - .git
    - .kitchen
    - Gemfile.lock
    - pytests_cache
  state_top:
    base:
      "*":
        - hugo
  pillars_from_directories:
    - source: pillars/
      dest: srv/pillar/
  pillars:
    top.sls:
      base:
        '*':
          - hugo

platforms:
  - name: ubuntu-14.04
    provisioner:
      salt_bootstrap_options: -X -x python3 -p git -p curl -p sudo stable 3005.1
  - name: ubuntu-18.04
    provisioner:
      salt_bootstrap_options: -X -x python3 -p git -p curl -p sudo stable 3005.1
  - name: ubuntu-22.04
    provisioner:
      salt_bootstrap_options: -X -x python3 -p git -p curl -p sudo stable 3005.1
suites:
  - name: boostrap

verifier:
  name: shell
  remote_exec: false
  command: python3 -m pytest -v tests/

